input_dir: .//
output_dir: .//
sample:
  scr: sample_submission.csv
  output: sample_submission.avro
destinations:
  scr: destinations.csv
  output: destinations.avro
test:
  scr: test.csv
  output: test.avro
train:
  scr: train.csv
  output: train.avro